export default [
    {
        title:"文字内容",
        name:'text',
        type:'textarea'
    },
    {
        title:"字体",
        name:'text',
        type:'select',
        options:[{
            label:'Apple',
            value:'Apple'
        },{
            label:'Orange',
            value:'Orange'
        }]
    },
    {
        title:"字号",
        name:'text',
        type:'select',
        options:[{
            label:'14',
            value:'14'
        },{
            label:'16',
            value:'16'
        }]
    },
    {
        title:"行高",
        name:'text',
        type:'select',
        options:[{
            label:'14',
            value:'14'
        },{
            label:'16',
            value:'16'
        }]
    }
]