export default [
    {
        name:1,
        id:1,
        text:'物理 <br/> 元本9',
        type:'text',
        style:{
          width:50,
          height:400,
          angle:0,
          top:40,
          left:800,
          color:'#000',
          fontSize:80,
          lineHeight:96,
          textAlign:'left',
          fontWeight:'bold'
        }
    },
    {
        name:2,
        id:2,
        type:'img',
        src:'https://tse3-mm.cn.bing.net/th?id=OIP.rJNHO8sYJpEhccdXGlN27gHaFj&w=277&h=207&c=7&o=5&dpr=2&pid=1.7',
        style:{
          width:100,
          height:200,
          angle:0,
          top:200,
          left:100,
          color:'#000',
          fontSize:14,
        }
    }
]